In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [7]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])


model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [14]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [15]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 100371.0781 - mae: 100371.0781 - val_loss: 98485.6172 - val_mae: 98485.6172
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99486.9688 - mae: 99486.9688 - val_loss: 96683.2500 - val_mae: 96683.2500
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96365.7266 - mae: 96365.7266 - val_loss: 92111.6641 - val_mae: 92111.6641
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 90295.8281 - mae: 90295.8281 - val_loss: 84625.2969 - val_mae: 84625.2969
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 81641.5469 - mae: 81641.5469 - val_loss: 75245.3594 - val_mae: 75245.3594
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 71974.4297 - mae: 71974.4297 - val_loss: 66148.5938 - val_mae: 66148.5938
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 63235.1992 - mae: 63235.1992 - val_loss: 58691.4727 - val_mae: 58691.4727
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 56940.6602 - mae: 56940.6602 - val_loss: 54147.6055 - val_mae: 54147.6055
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 53345.4609 - mae: 53345.4609 - val_loss: 51784.3750 - val_mae: 51784.3750
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 51552.0547 - mae: 51552.0547 - val_loss: 50847.3320 - val_mae: 50847.3320
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 50766.3594 - mae: 50766.3594 - val_loss: 50554.5977 - val_mae: 50554.5977
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 50428.5586 - mae: 50428.5586 - val_loss: 50444.7852 - val_mae: 50444.7852
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50258.6172 - mae: 50258.6172 - val_loss: 50395.9297 - val_mae: 50395.9297
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 50158.6641 - mae: 50158.6641 - val_loss: 50360.8516 - val_mae: 50360.8516
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 50095.3711 - mae: 50095.3711 - val_loss: 50331.7891 - val_mae: 50331.7891
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50037.3164 - mae: 50037.3164 - val_loss: 50304.7344 - val_mae: 50304.7344
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 49990.6367 - mae: 49990.6367 - val_loss: 50292.7930 - val_mae: 50292.7930
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 49945.9844 - mae: 49945.9844 - val_loss: 50284.0742 - val_mae: 50284.0742
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 49913.1523 - mae: 49913.1523 - val_loss: 50261.8281 - val_mae: 50261.8281
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 49883.7773 - mae: 49883.7773 - val_loss: 50246.8828 - val_mae: 50246.8828
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 49855.4258 - mae: 49855.4258 - val_loss: 50236.2188 - val_mae: 50236.2188
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 49833.2969 - mae: 49833.2969 - val_loss: 50239.3516 - val_mae: 50239.3516
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49811.3906 - mae: 49811.3906 - val_loss: 50214.5078 - val_mae: 50214.5078
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 49786.4883 - mae: 49786.4883 - val_loss: 50222.7891 - val_mae: 50222.7891
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 49763.3906 - mae: 49763.3906 - val_loss: 50199.2031 - val_mae: 50199.2031
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 49747.4023 - mae: 49747.4023 - val_loss: 50193.4727 - val_mae: 50193.4727
Epoch 27/100
250/250 [==============================] - 1s 2ms/step - loss: 49726.9453 - mae: 49726.9453 - val_loss: 50190.8477 - val_mae: 50190.8477
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 49711.1797 - mae: 49711.1797 - val_loss: 50182.8477 - val_mae: 50182.8477
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 49697.6445 - mae: 49697.6445 - val_loss: 50186.4727 - val_mae: 50186.4727
Epoch 30/100
250/250 [==============================] - 1s 2ms/step - loss: 49678.4297 - mae: 49678.4297 - val_loss: 50191.5898 - val_mae: 50191.5898
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49667.0000 - mae: 49667.0000 - val_loss: 50180.7812 - val_mae: 50180.7812
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49653.4375 - mae: 49653.4375 - val_loss: 50171.1406 - val_mae: 50171.1406
Epoch 33/100
250/250 [==============================] - 1s 2ms/step - loss: 49637.8086 - mae: 49637.8086 - val_loss: 50173.0859 - val_mae: 50173.0859
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49624.5273 - mae: 49624.5273 - val_loss: 50163.0938 - val_mae: 50163.0938
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49612.8906 - mae: 49612.8906 - val_loss: 50172.8438 - val_mae: 50172.8438
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 49601.4844 - mae: 49601.4844 - val_loss: 50167.8281 - val_mae: 50167.8281
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 49588.3398 - mae: 49588.3398 - val_loss: 50169.0508 - val_mae: 50169.0508
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 49579.4453 - mae: 49579.4453 - val_loss: 50162.9297 - val_mae: 50162.9297
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 49566.9062 - mae: 49566.9062 - val_loss: 50169.8633 - val_mae: 50169.8633
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49555.7188 - mae: 49555.7188 - val_loss: 50163.7227 - val_mae: 50163.7227
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.3359 - mae: 49547.3359 - val_loss: 50159.8281 - val_mae: 50159.8281
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49535.9336 - mae: 49535.9336 - val_loss: 50156.5938 - val_mae: 50156.5938
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49525.4297 - mae: 49525.4297 - val_loss: 50162.5352 - val_mae: 50162.5352
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 49522.4609 - mae: 49522.4609 - val_loss: 50157.9570 - val_mae: 50157.9570
Epoch 45/100
250/250 [==============================] - 1s 2ms/step - loss: 49512.9219 - mae: 49512.9219 - val_loss: 50163.6289 - val_mae: 50163.6289
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49506.4844 - mae: 49506.4844 - val_loss: 50162.0938 - val_mae: 50162.0938
Epoch 47/100
250/250 [==============================] - 1s 2ms/step - loss: 49494.8906 - mae: 49494.8906 - val_loss: 50161.8594 - val_mae: 50161.8594
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 49488.5078 - mae: 49488.5078 - val_loss: 50155.3828 - val_mae: 50155.3828
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 49479.9297 - mae: 49479.9297 - val_loss: 50155.0273 - val_mae: 50155.0273
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49474.1680 - mae: 49474.1680 - val_loss: 50164.2148 - val_mae: 50164.2148
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49465.1055 - mae: 49465.1055 - val_loss: 50156.7578 - val_mae: 50156.7578
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49462.8047 - mae: 49462.8047 - val_loss: 50149.5508 - val_mae: 50149.5508
Epoch 53/100
250/250 [==============================] - 1s 2ms/step - loss: 49452.1484 - mae: 49452.1484 - val_loss: 50165.0586 - val_mae: 50165.0586
Epoch 54/100
250/250 [==============================] - 1s 2ms/step - loss: 49447.1602 - mae: 49447.1602 - val_loss: 50163.2812 - val_mae: 50163.2812
Epoch 55/100
250/250 [==============================] - 1s 2ms/step - loss: 49442.7305 - mae: 49442.7305 - val_loss: 50165.1289 - val_mae: 50165.1289
Epoch 56/100
250/250 [==============================] - 1s 2ms/step - loss: 49433.5195 - mae: 49433.5195 - val_loss: 50164.2344 - val_mae: 50164.2344
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 49431.0742 - mae: 49431.0742 - val_loss: 50166.6250 - val_mae: 50166.6250
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 49425.1406 - mae: 49425.1406 - val_loss: 50169.6680 - val_mae: 50169.6680
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 49418.6523 - mae: 49418.6523 - val_loss: 50181.7344 - val_mae: 50181.7344
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 49413.2578 - mae: 49413.2578 - val_loss: 50169.3438 - val_mae: 50169.3438
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 49409.2578 - mae: 49409.2578 - val_loss: 50185.5000 - val_mae: 50185.5000
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 49401.7969 - mae: 49401.7969 - val_loss: 50187.1680 - val_mae: 50187.1680

In [16]:
%load_ext tensorboard

In [17]:
%tensorboard --logdir regressionlogs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "C:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "C:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [18]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 0s 1ms/step - loss: 50149.5508 - mae: 50149.5508
Test Loss: 50149.55078125, Test MAE: 50149.55078125

In [19]:
model.save('regression_model.h5')

c:\Users\indra\OneDrive\Desktop\END TO END ANN PROJECT\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(